import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);
		int TotalChild = 0;
		int TwoChild = 0;
		int ThreeChild = 0;
		int FourOrMoReChild = 0;
		for (int i=0 ; i<T; i++) {
			boolean boy = false;
			boolean girl = false;
			int numOfChild = 0;
			while (!(boy && girl)) {
				if (generator.nextDouble() < 0.5) {
					boy = true;
				} else {
					girl = true;
				}
				numOfChild++;
			}
			TotalChild += numOfChild;
			if (numOfChild == 2) {
				TwoChild++;
			} else if (numOfChild == 3) {
				ThreeChild++;
			} else {
				FourOrMoReChild++;
			}
		}
		double Average = (double) TotalChild/T;
		String max = "2";
		if (ThreeChild > TwoChild && ThreeChild >= FourOrMoReChild){
			max = "3";
		} else if (FourOrMoReChild > ThreeChild && FourOrMoReChild > TwoChild) {
			max = "4 or more";
		}
		System.out.println("Average: " + Average + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + TwoChild);
		System.out.println("Number of families with 3 children: " + ThreeChild);
		System.out.println("Number of families with 4 or more children: " + FourOrMoReChild);
		System.out.println("The most common number of children is " + max + ".");
	}
}


